module.exports = {
  attendanceList: [{
    "id": 1,
    "first_name": "Hastie",
    "last_name": "Peppard",
    "gender": "Male",
    "language": "Maltese"
  }, {
    "id": 2,
    "first_name": "Layla",
    "last_name": "Garron",
    "gender": "Female",
    "language": "Bengali"
  }, {
    "id": 3,
    "first_name": "Lorettalorna",
    "last_name": "Restieaux",
    "gender": "Female",
    "language": "Dari"
  }, {
    "id": 4,
    "first_name": "Dorothee",
    "last_name": "Solloway",
    "gender": "Female",
    "language": "French"
  }, {
    "id": 5,
    "first_name": "Salomon",
    "last_name": "Ewers",
    "gender": "Male",
    "language": "Korean"
  }, {
    "id": 6,
    "first_name": "Vernice",
    "last_name": "Carillo",
    "gender": "Polygender",
    "language": "French"
  }, {
    "id": 7,
    "first_name": "Jamesy",
    "last_name": "Dodridge",
    "gender": "Male",
    "language": "Gujarati"
  }, {
    "id": 8,
    "first_name": "Christie",
    "last_name": "Collishaw",
    "gender": "Male",
    "language": "Spanish"
  }],
  studentList: [{
    "id": 1,
    "gender": "Male",
    "last_name": "Peppard",
    "first_name": "Hastie",
    "language": "Maltese"
  }, {
    "id": 2,
    "gender": "Female",
    "first_name": "Layla",
    "last_name": "Garron",
    "language": "Bengali"
  }, {
    "id": 3,
    "gender": "Female",
    "first_name": "Lorettalorna",
    "last_name": "Restieaux",
    "language": "Dari"
  }, {
    "id": 4,
    "gender": "Female",
    "first_name": "Dorothee",
    "last_name": "Solloway",
    "language": "French"
  }, {
    "id": 5,
    "gender": "Male",
    "first_name": "Salomon",
    "last_name": "Ewers",
    "language": "Korean"
  }, {
    "id": 6,
    "gender": "Polygender",
    "first_name": "Vernice",
    "last_name": "Carillo",
    "language": "French"
  }, {
    "id": 7,
    "gender": "Male",
    "first_name": "Jamesy",
    "last_name": "Dodridge",
    "language": "Gujarati"
  }, {
    "id": 8,
    "gender": "Male",
    "first_name": "Christie",
    "last_name": "Collishaw",
    "language": "Spanish"
  }],
};