"use strict";

const people = [
    "Markovič,Marianna,33,Slovakia,shooting*improv*unicycling*cooking*writing",
    "Riška,Gejza,31,Slovakia,fencing*archery*piano*sky-diving*dance",
    "Βούλγαρης,Εύρυτος,30,Greece,conditioning/weight-training*dance*sky-diving*juggling*unicycling",
    "Peterson,Phillip,25,United_States,programming*geocaching*geocaching*reading*backpacking/camping",
    "Livescu,Gabriela,32,Romania,geocaching*kendo*juggling*origami*backpacking/camping",
    "Imanov,Uulkiz,29,Kyrgyz_Republic,juggling*kickboxing*unicycling*surfing*programming",
    "Hudáček,Edmund,30,Slovakia,dance*geocaching*backpacking/camping*writing*karaoke",
    "Κορωναίος,Ηρόδοτος,29,Greece,origami*fermenting*origami*karaoke*surfing",
    "Niyaas,Sushma,34,Nepal,origami*improv*sky-diving*karaoke*piano",
    "Μέλιοι,Μίλων,31,Greece,shooting*kickboxing*fencing*surfing*kendo",
    "Paško,Amália,33,Slovakia,kendo*painting*sky-diving*shooting*piano",
    "Gudelj,Zana,29,Bosnia_and_Herzegovina,dance*improv*fermenting*writing*kickboxing",
    "Edit,Ördög,31,Hungary,backpacking/camping*fencing*knitting*backpacking/camping*painting",
    "Miclea,Călin,29,Romania,piano*knitting*shooting*knitting*unicycling",
    "Amanda,Gyöngyösi,23,Hungary,painting*writing*geocaching*surfing*geocaching",
    "Gruia,Nicuță,26,Romania,painting*fencing*improv*knitting*painting",
    "刚,莫,36,China,surfing*knitting*surfing*shooting*cooking",
    "Popescu,Valter,22,Romania,unicycling*backpacking/camping*origami*fencing*kickboxing",
    "Mulder,Eelco,30,Netherlands,backpacking/camping*juggling*piano*origami*unicycling",
    "健太,長谷川,29,Japan,origami*shooting*piano*shooting*archery",
    "Păunescu,Aura,30,Romania,unicycling*knitting*sky-diving*surfing*painting",
    "Armășescu,Ica,33,Romania,juggling*archery*dance*yoga*backpacking/camping",
    "Κουταλιανός,Επειός,35,Greece,surfing*fencing*piano*unicycling*kickboxing",
    "Pușcaș,Ionelia,31,Romania,yoga*fencing*surfing*writing*backpacking/camping",
    "Chiến,Cao,32,Vietnam,kendo*juggling*backpacking/camping*knitting*yoga",
    "Μαλαξός,Ελισσώνας,26,Greece,painting*origami*fermenting*yoga*fencing",
    "Hahn,Simon,32,Germany,cooking*reading*kickboxing*juggling*improv",
    "Chebac,Petronela,25,Romania,shooting*painting*fermenting*origami*painting",
    "Teichmann,Linda,28,Germany,fermenting*shooting*fencing*improv*writing",
    "Καραμήτσος,Θεόδοτος,36,Greece,origami*fermenting*yoga*knitting*kendo",
    "Lup,Anica,33,Romania,cooking*knitting*unicycling*fermenting*sky-diving",
    "Thomson,Edward,28,England,painting*backpacking/camping*yoga*fermenting*piano",
    "Akande,Kayode,32,Nigeria,sky-diving*kendo*juggling*programming*writing",
    "Mayer,Sandra,22,Austria,geocaching*knitting*geocaching*geocaching*geocaching",
    "Cocea,Severina,24,Romania,yoga*sky-diving*cooking*geocaching*surfing",
    "Csaba,Sárosi,31,Hungary,shooting*backpacking/camping*surfing*dance*dance",
    "Lawrence,Arthur,22,United_States,kickboxing*unicycling*cooking*writing*archery",
    "Rusca,Blanduzia,32,Romania,fencing*painting*karaoke*shooting*surfing",
    "Azatbekov,Kairat,32,Kyrgyz_Republic,sky-diving*geocaching*yoga*knitting*kendo",
    "Евдокимовa,Алла,36,Russia,improv*geocaching*sky-diving*kendo*Jiu-Jitsu",
    "Demir,Osman,34,Turkey,shooting*reading*knitting*kendo*knitting",
    "Dascălu,Stela,36,Romania,knitting*sky-diving*reading*yoga*cooking",
    "Lam,Henry,24,Canada,sky-diving*sky-diving*origami*surfing*kendo",
    "Posteucă,Mihai,26,Romania,geocaching*juggling*geocaching*painting*reading",
    "Timică,Rafila,36,Romania,backpacking/camping*geocaching*fencing*piano*surfing",
    "Rayamajhee,Bhawana,28,Nepal,surfing*kendo*programming*archery*yoga",
    "Ζάχος,Ισαάκιος,26,Greece,geocaching*juggling*painting*piano*geocaching",
    "Sabău,Cosmina,27,Romania,geocaching*cooking*knitting*yoga*sky-diving",
    "佳,孟,32,China,piano*dance*geocaching*improv*origami",
    "Halliday,Jamie,32,New_Zealand,yoga*knitting*sky-diving*yoga*programming",
    "Roháč,Marcela,23,Slovakia,kickboxing*improv*reading*surfing*reading",
    "Bailey,Isabel,26,England,kendo*reading*kendo*yoga*painting",
    "Papacioc,Simi,31,Romania,painting*programming*surfing*fencing*fencing",
    "Shah,Saanvi,29,India,kickboxing*yoga*dance*Jiu-Jitsu*surfing",
    "Şener,Tevfik,23,Turkey,cooking*backpacking/camping*kendo*archery*conditioning/weight-training",
    "Kairatov,Jazgul,23,Kyrgyz_Republic,yoga*writing*conditioning/weight-training*reading*kendo",
    "Pușcariu,Natașa,28,Romania,piano*juggling*sky-diving*knitting*backpacking/camping",
    "Lascu,Silvana,29,Romania,origami*shooting*shooting*improv*unicycling",
    "Bulcsú,Falusi,35,Hungary,geocaching*cooking*fencing*painting*archery",
    "Lebrun,Clotilde,33,France,archery*fencing*sky-diving*fermenting*cooking",
    "Torres,Gabriela,35,Mexico,unicycling*geocaching*conditioning/weight-training*backpacking/camping*painting",
    "Βούλγαρης,Εύηνος,27,Greece,fencing*knitting*kickboxing*painting*kendo",
    "Pawlak,Konrad,25,Poland,writing*kendo*cooking*conditioning/weight-training*kendo",
    "Agrawal,Tulsi,33,Nepal,knitting*kickboxing*piano*archery*geocaching",
    "Capka,Štefánia,27,Slovakia,improv*dance*geocaching*programming*geocaching",
    "Bailey,Callum,23,England,yoga*surfing*backpacking/camping*geocaching*fermenting",
    "Lopchan,Ashraya,28,Nepal,writing*origami*origami*cooking*writing",
    "Καλλιγάς,Μενέλαος,29,Greece,origami*reading*Jiu-Jitsu*fencing*geocaching",
    "Rolland,Laura,36,France,origami*sky-diving*cooking*geocaching*painting",
    "Chelaru,Iris,33,Romania,knitting*improv*writing*cooking*shooting",
    "Enescu,Petru,24,Romania,fermenting*knitting*programming*karaoke*kendo",
    "Γεωργιάδης,Κήρυξ,34,Greece,backpacking/camping*yoga*surfing*surfing*improv",
    "МИХАЙЛОВА,Любен,31,Bulgaria,surfing*surfing*knitting*cooking*fencing",
    "Farina,Davide,23,Italy,programming*geocaching*fencing*Jiu-Jitsu*archery",
    "Lenóra,Zsolnai,31,Hungary,reading*shooting*writing*conditioning/weight-training*kendo",
    "Γερμανός,Αρκεσίλαος,24,Greece,juggling*Jiu-Jitsu*fencing*painting*juggling",
    "Κωνσταντόπουλος,Ελίνα,26,Greece,conditioning/weight-training*juggling*conditioning/weight-training*shooting*fermenting",
    "Κουντουριώτης,Μεταγένης,28,Greece,writing*dance*kickboxing*improv*unicycling",
    "Carrillo,Elena,26,Mexico,reading*backpacking/camping*dance*cooking*kickboxing",
    "Κρεστενίτης,Γλαύκος,36,Greece,piano*geocaching*archery*kickboxing*archery",
    "Ευταξίας,Αφαρέας,22,Greece,programming*dance*origami*writing*Jiu-Jitsu",
    "Alvarez,Jairo,31,Colombia,kendo*cooking*karaoke*sky-diving*cooking",
    "Franke,Dominic,31,Germany,juggling*programming*fencing*surfing*kickboxing",
    "Dowling,Trinity,33,New_Zealand,fencing*painting*origami*knitting*fencing",
    "Celibidache,Dimitra,35,Romania,programming*backpacking/camping*unicycling*yoga*kickboxing",
    "Tádé,Fehér,29,Hungary,sky-diving*geocaching*kickboxing*geocaching*Jiu-Jitsu",
    "Stoenescu,Hortensia,33,Romania,conditioning/weight-training*kickboxing*kickboxing*yoga*kendo",
    "Walker,Tyler,27,Australia,reading*karaoke*kendo*painting*improv",
    "Αποστολίδης,Μέντωρ,32,Greece,painting*writing*backpacking/camping*painting*surfing",
    "Jesús,Esperanza_de,35,Mexico,improv*cooking*cooking*juggling*conditioning/weight-training",
    "Santos,Rigoberto_de_los,23,Mexico,karaoke*kickboxing*writing*painting*kickboxing",
    "János,Magyar,25,Hungary,piano*fermenting*unicycling*kickboxing*Jiu-Jitsu",
    "Stavarache,Cristina,31,Romania,conditioning/weight-training*dance*reading*knitting*improv",
    "Moser,Clemens,26,Austria,unicycling*writing*unicycling*archery*conditioning/weight-training",
    "Căciulescu,Luiza,32,Romania,programming*fermenting*geocaching*origami*juggling",
    "Madej,Lesana,26,Slovakia,yoga*kendo*shooting*piano*yoga",
    "Topor,Dorel,34,Romania,shooting*programming*painting*piano*geocaching",
    "Douglas,Zachary,22,New_Zealand,reading*archery*karaoke*yoga*knitting",
    "Krištof,Tichomír,26,Slovakia,surfing*painting*knitting*painting*shooting",
    "Miculescu,Olimpia,31,Romania,painting*juggling*improv*karaoke*writing",
    "Kolesár,Danica,29,Slovakia,juggling*origami*improv*improv*fermenting",
    "Sătmărean,Lavinia,28,Romania,sky-diving*unicycling*kendo*Jiu-Jitsu*kickboxing",
    "Βιλαέτης,Γανυμήδης,35,Greece,Jiu-Jitsu*improv*shooting*programming*juggling",
    "ענבר,רותי,23,Israel,piano*surfing*fermenting*conditioning/weight-training*conditioning/weight-training",
    "Adams,Zak,23,England,dance*writing*painting*origami*piano",
    "Patrícia,Csillag,24,Hungary,Jiu-Jitsu*piano*piano*backpacking/camping*archery",
    "Riško,Milena,28,Slovakia,programming*cooking*conditioning/weight-training*programming*shooting",
    "Κορομηλάς,Ευρυμέδων,28,Greece,karaoke*fencing*kendo*kendo*reading",
    "Leblanc,Sophie,29,Canada,backpacking/camping*programming*piano*painting*piano",
    "Иванов,Оскар,36,Russia,reading*sky-diving*painting*unicycling*painting",
    "الغربي,السيدة,30,Tunisia,unicycling*cooking*piano*surfing*writing",
    "Thakuri,Gita,22,Nepal,piano*karaoke*backpacking/camping*conditioning/weight-training*programming",
    "فرجی,عسل,33,Iran,improv*kickboxing*dance*programming*fermenting",
    "Demiral,Ulvi,32,Turkey,juggling*painting*writing*karaoke*kendo",
    "Berry,Amy,35,New_Zealand,sky-diving*sky-diving*programming*karaoke*painting",
    "Sobczak,Julian,26,Poland,improv*knitting*unicycling*painting*cooking",
    "Davidovici,Gică,22,Romania,yoga*fencing*piano*karaoke*Jiu-Jitsu",
    "Μητσοτάκης,Επειός,34,Greece,conditioning/weight-training*reading*Jiu-Jitsu*sky-diving*knitting",
    "Konrád,Hargitai,31,Hungary,karaoke*archery*backpacking/camping*sky-diving*writing",
    "Chhetri,Mina,29,Nepal,piano*fencing*conditioning/weight-training*writing*improv",
    "Barron,Gerardo,23,Mexico,yoga*surfing*cooking*origami*Jiu-Jitsu",
    "Cools,Maxime,23,Belgium,fermenting*piano*programming*kickboxing*reading",
    "Καλύβας,Δημοφών,30,Greece,piano*fencing*shooting*reading*archery",
    "Жердев,Рoмaна,33,Ukraine,painting*Jiu-Jitsu*cooking*surfing*cooking",
    "Bednárik,Edmund,29,Slovakia,surfing*origami*fermenting*fermenting*improv",
    "Firulescu,Lelia,31,Romania,unicycling*sky-diving*conditioning/weight-training*knitting*surfing",
    "Ζέρβας,Θεοφάνης,29,Greece,karaoke*surfing*cooking*Jiu-Jitsu*piano",
    "Williamson,Daniel,32,United_States,writing*origami*sky-diving*improv*dance",
    "Neacșu,Petrică,31,Romania,programming*archery*backpacking/camping*Jiu-Jitsu*archery",
    "Neagu,Ozana,28,Romania,kendo*unicycling*geocaching*surfing*juggling",
    "Fajardo,Mariana,25,Colombia,shooting*shooting*dance*programming*shooting",
    "Ján,Ľubomíra,26,Slovakia,kendo*backpacking/camping*Jiu-Jitsu*dance*piano",
    "Turanlı,Faiq,35,Azerbaijan,sky-diving*conditioning/weight-training*reading*knitting*Jiu-Jitsu",
    "Zénó,Varjas,28,Hungary,kickboxing*juggling*surfing*fermenting*fermenting",
    "Δουμπιώτης,Δαμέας,26,Greece,unicycling*Jiu-Jitsu*knitting*reading*surfing",
    "Štefanovič,Oleg,35,Slovakia,cooking*juggling*conditioning/weight-training*Jiu-Jitsu*piano",
    "Cruz,Laura,23,Spain,kendo*yoga*Jiu-Jitsu*piano*sky-diving",
    "Ghideanu,Otilia,34,Romania,fermenting*kendo*conditioning/weight-training*programming*kendo",
    "Thakur,Nishant,33,Nepal,improv*fermenting*surfing*archery*surfing",
    "Bhattarai,Rohit,31,Nepal,reading*kendo*backpacking/camping*yoga*sky-diving",
    "Dobrescu,Silviu,32,Romania,fencing*kendo*fencing*cooking*juggling",
    "Almașanu,Ilona,30,Romania,kickboxing*Jiu-Jitsu*origami*writing*painting",
    "예진,주,36,Korea,fencing*juggling*fencing*reading*fencing",
    "Jímenez,Juan,33,Mexico,kendo*karaoke*origami*conditioning/weight-training*knitting",
    "Bădărău,Georgian,29,Romania,sky-diving*shooting*archery*knitting*dance",
    "Parajuli,Bikram,33,Nepal,conditioning/weight-training*kendo*surfing*surfing*fermenting",
    "Martinelli,Giuseppe,30,Italy,karaoke*dance*geocaching*karaoke*reading",
    "Mustafa,Karanfil,30,Turkey,reading*knitting*reading*sky-diving*shooting",
    "Filipescu,Stana,26,Romania,reading*cooking*geocaching*Jiu-Jitsu*fermenting",
    "Marcel,Rakonczai,22,Hungary,karaoke*karaoke*writing*fencing*shooting",
    "Valentín,Zina,23,Slovakia,karaoke*Jiu-Jitsu*fermenting*dance*backpacking/camping",
    "Νικολάκος,Ελισσώνας,25,Greece,piano*reading*writing*sky-diving*Jiu-Jitsu",
    "Cernat,Pavel,22,Romania,archery*conditioning/weight-training*knitting*unicycling*writing",
    "Barajas,Margarita,34,Mexico,archery*yoga*surfing*fencing*reading",
    "Davis,Carolyn,25,United_States,archery*fermenting*writing*reading*geocaching",
    "Lascu,Nelu,36,Romania,Jiu-Jitsu*programming*karaoke*unicycling*reading",
    "Bogati,Birat,23,Nepal,backpacking/camping*conditioning/weight-training*cooking*fencing*reading",
    "Arnaud,Maryam,33,France,kendo*piano*archery*dance*surfing",
    "Ranjitkar,Ghanashyam,31,Nepal,kickboxing*programming*sky-diving*improv*geocaching",
    "Vlna,Svetozár,22,Slovakia,juggling*programming*backpacking/camping*kendo*fencing",
    "Majeský,Iľja,25,Slovakia,kickboxing*yoga*yoga*Jiu-Jitsu*kickboxing",
    "Maes,Lucie,26,Belgium,origami*cooking*conditioning/weight-training*surfing*backpacking/camping",
    "Bucurescu,Lavinia,32,Romania,shooting*knitting*conditioning/weight-training*archery*improv",
    "Κρεστενίτης,Ιππίας,27,Greece,geocaching*juggling*cooking*painting*karaoke",
    "Guerin,Yohan,24,France,unicycling*fermenting*juggling*yoga*reading",
    "Ban,Seema,25,Nepal,programming*yoga*kickboxing*origami*writing",
    "Moța,Petruț,26,Romania,origami*piano*dance*surfing*juggling",
    "Gulistanov,Masuda,29,Kyrgyz_Republic,conditioning/weight-training*juggling*shooting*fermenting*geocaching",
    "Dhital,Gagan,34,Nepal,archery*juggling*unicycling*painting*surfing",
    "Avramescu,Anton,32,Romania,reading*piano*conditioning/weight-training*origami*fencing",
    "McKenzie,Tessa,26,New_Zealand,juggling*knitting*painting*juggling*fencing",
    "Deuba,Bharat,27,Nepal,kickboxing*writing*programming*improv*painting",
    "Αλεξάνδρου,Ελίνα,34,Greece,reading*unicycling*yoga*fermenting*fencing",
    "Castro,Roger,32,United_States,geocaching*juggling*karaoke*yoga*geocaching",
    "Toneanu,Cătălin,24,Romania,painting*programming*programming*juggling*unicycling",
    "Râpeanu,Zeno,31,Romania,backpacking/camping*geocaching*conditioning/weight-training*fermenting*cooking",
    "Petrescu,Codrina,28,Romania,cooking*unicycling*shooting*kickboxing*conditioning/weight-training",
    "Șerbănescu,Mădălina,26,Romania,knitting*unicycling*origami*cooking*conditioning/weight-training",
    "Brunovský,Jarmila,35,Slovakia,geocaching*programming*cooking*improv*dance",
    "Spirescu,Nadia,22,Romania,kendo*piano*writing*karaoke*writing",
    "Bozga,Dumitrana,23,Romania,painting*cooking*programming*archery*archery",
    "Little,Nicole,26,United_States,Jiu-Jitsu*cooking*programming*kendo*programming",
    "Salamatov,Uulkan,31,Kyrgyz_Republic,juggling*sky-diving*kickboxing*writing*unicycling",
    "Αρβανίτης,Δίας,30,Greece,cooking*reading*karaoke*improv*piano",
    "Crețu,Zeno,26,Romania,painting*writing*yoga*backpacking/camping*archery",
    "Nóra,Németh,22,Hungary,geocaching*geocaching*surfing*painting*programming",
    "Preoteasa,Gabi,30,Romania,piano*geocaching*fermenting*karaoke*Jiu-Jitsu",
    "Neamțu,Oliviu,27,Romania,piano*sky-diving*origami*backpacking/camping*improv",
    "Dupont,Lukas,34,Belgium,piano*sky-diving*kendo*origami*dance",
    "Ζέρβας,Αρχίδαμος,24,Greece,karaoke*kendo*origami*programming*backpacking/camping",
    "Joss,Mya,29,New_Zealand,conditioning/weight-training*improv*shooting*geocaching*kendo",
    "Κοτζιάς,Εύβουλος,30,Greece,fencing*dance*origami*backpacking/camping*reading",
    "Κουβέλης,Κίμων,23,Greece,knitting*kendo*karaoke*sky-diving*origami",
    "明日香,藤井,34,Japan,shooting*surfing*improv*sky-diving*sky-diving",
    "Thoma,Sebastian,21,Germany,Jiu-Jitsu*fencing*karaoke*surfing*reading",
    "Enescu,Emil,28,Romania,juggling*fermenting*unicycling*shooting*backpacking/camping",
    "Péter,Bálint,25,Hungary,fermenting*geocaching*surfing*kickboxing*shooting",
    "Andoni,Simion,34,Romania,programming*painting*kickboxing*improv*backpacking/camping",
    "Stewart,Brittany,33,United_States,fermenting*reading*geocaching*shooting*backpacking/camping",
];

const hobbyToMatch = "reading";
const lastName = []
const firstName = []
const age = []
const country = []
const hobbies = []


// Example output
// "Brittany S. (33) from United States has the following hobbies: fermenting, reading, geocaching, shooting and backpacking/camping."

for (let i = 0; i < people.length; i++) {
    lastName[i] = people[i].split(",")[0]
    firstName[i] = people[i].split(",")[1]
    age[i] = people[i].split(",")[2]
    country[i] = people[i].split(",")[3]
    hobbies[i] = people[i].split(",")[4]
}

for (let i = 0; i < people.length; i++) {
    if (hobbies[i].includes(hobbyToMatch)) {
        console.log(`${firstName[i]} ${lastName[i][0] + "."} (${age[i]}) from ${country[i].replace(/\_/g, " ")} has the following hobbies: ${hobbies[i].replace(/\*/g, ", ").replace(/, ([^,]*)$/, ' and $1')} \n`)
    }
}
    